<a href="https://colab.research.google.com/github/luizmaeaspillaga/LinearAlgebra_2ndSem/blob/main/Aspillaga_Assignment_5_Matrix_Operations_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for CHE

## Laboratory 6 : Matrix Operations

## Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

The transpose of a matrix is obtained by transferring the data from the rows to the columns and the data from the columns to the rows. If we have an array of shape (X, Y), the array's transposition will have the same shape (Y, X).

One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for *A* matrix  its transpose is denoted as *A*. So for example:

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [2]:
A = np.array([
    [2 ,1, 3],
    [3, 1, 5],
    [0, -3, 3]
])
A

array([[ 2,  1,  3],
       [ 3,  1,  5],
       [ 0, -3,  3]])

In [3]:
AT1 = np.transpose(A)
AT1

array([[ 2,  3,  0],
       [ 1,  1, -3],
       [ 3,  5,  3]])

In [4]:
AT2 = A.T

In [5]:
np.array_equiv(AT1, AT2)

True

In [6]:
B = np.array([
    [2,1,3,5],
    [5,8,9,7],
])
B.shape

(2, 4)

In [7]:
np.transpose(B).shape

(4, 2)

In [8]:
B.T.shape

(4, 2)

**Try to create your own matrix (you can try non-squares) to test transposition.**

In [9]:
A = np.array([
    [2 ,1, 3,7],
    [3, 1, 5,9],
    [0, -3, 3,8]
])
A

array([[ 2,  1,  3,  7],
       [ 3,  1,  5,  9],
       [ 0, -3,  3,  8]])

In [10]:
AT1 = np.transpose(A)
AT1

array([[ 2,  3,  0],
       [ 1,  1, -3],
       [ 3,  5,  3],
       [ 7,  9,  8]])

In [11]:
AT2 = A.T

In [12]:
np.array_equiv(AT1, AT2)

True

In [13]:
B = np.array([
    [2,1,3,5,8,9],
    [5,8,9,7,6,7],
])
B.shape

(2, 6)

In [14]:
np.transpose(B).shape


(6, 2)

In [15]:
B.T.shape

(6, 2)

# Dot Product/Cross Product

This function returns the dot product of two arrays. It's the same as matrix multiplication for 2-D vectors. It is the inner product of the vectors for 1-D arrays. It is a sum-product over the last axis of a and the second-last axis of b for N-dimensional arrays.

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [16]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [2,1,3],
    [3,1,5]
])

In [17]:
np.dot(X,Y)

array([[ 8,  3, 13],
       [ 3,  1,  5]])

In [18]:
X.dot(Y)

array([[ 8,  3, 13],
       [ 3,  1,  5]])

In [19]:
X @ Y

array([[ 8,  3, 13],
       [ 3,  1,  5]])

In [20]:
np.matmul(X,Y)

array([[ 8,  3, 13],
       [ 3,  1,  5]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4&6\\5&-2&5\\0&1&5\end{bmatrix}, B = \begin{bmatrix}1&1&1\\3&3&3\end{bmatrix}, 
C = \begin{bmatrix}0&1&1&5\\1&1&2&5\\2&1&3&4\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

Rule 1: The two matrices in question must have the same inner dimensions.

In [21]:
A = np.array([
    [2, 4, 6],
    [5, -2, 5],
    [0, 1, 5]
])
B = np.array([
    [1, 1, 1],
    [3, 3, 3]
])
C = np.array([
    [0, 1, 1, 5],
    [1, 1, 2 ,5],
    [2, 1, 3, 4]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 3)
(2, 3)
(3, 4)


In [22]:
A @ C

array([[16, 12, 28, 54],
       [ 8,  8, 16, 35],
       [11,  6, 17, 25]])

In [23]:
B @ C

array([[ 3,  3,  6, 14],
       [ 9,  9, 18, 42]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [24]:
A @ B.T

array([[12, 36],
       [ 8, 24],
       [ 6, 18]])

In [25]:
X = np.array([
    [2,1,3]
])
Y = np.array([
    [2,3],
    [0,5],
    [1,9]
])
print(X.shape)
print(Y.shape)

(1, 3)
(3, 2)


In [26]:
Y.T @ X

ValueError: ignored

And you can see that when you try to multiply A and B, it returns ValueError pertaining to matrix shape mismatch.

In [30]:
X = np.array([
    [2,1],
    [4,5],
    [6,9]
])
Y = np.array([
    [2,3],
    [0,5],
    [1,9]
])
print(X.shape)
print(Y.shape)

(3, 2)
(3, 2)


In [29]:
Y.T @ X

array([[ 10,  11],
       [ 80, 109]])

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

Dot product in matrix refers to the summation of all products of each entry. It is composed of 6 unique properties.

The **first property** proves that the dot product of A and B is not equal to the dot product of B and A. This also means that the commutative property of multiplication is not applicable to matrices.

The **second property** shows that the product of A and dot product of B and C is equal to the product of C and dot product of A and B. This shows the associative property of multiplication.

The **third property** of the dot product of matrices shows that the A multiplied by the sum of B and C is equal to the sum of the product of A and B and product of A and C. This presents the distributive property of multiplication. 

The **fourth property** is somehow similar to the third property, where A is distributed to both B and C. It is equal to the sum of the product of B and A, and the product of C and A. 

The **fifth property** shows that when A is  multiplied by I the products will always be A, regardless of the order in which multiplication was performed. This shows the multiplicative identity property.

The **last property** shows that any matrix multiplied by zero the product will always be equal to zero. This shows the multiplicative property of zero.  


In [31]:
A = np.array([
    [2,1,3],
    [3,1,2],
    [0,9,8]
])
B = np.array([
    [5,2,3],
    [6,1,9],
    [4,5,9]
])
C = np.array([
    [0,0,1],
    [2,0,0],
    [0,3,0]
])

In [32]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.array_equal(a_dot_z,z_mat)

True

In [36]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

In [37]:
A = np.array([
    [4,3,2,1],
    [5,6,7,8],
    [9,10,11,12],
    [5,6,7,5]
])
B = np.array([
    [0,0,0,2],
    [0,0,2,3],
    [0,2,1,3],
    [3,1,5,3]
])
C= np.array([
  [2,1,3,5],
  [6,7,8,9],
  [9,8,6,4],
  [12,13,14,15]
])

In [38]:
M = A.dot(B)
M2 = A.dot(C)
S = B.dot(C)
L = B + C
G = M + M2

In [39]:
M = B.dot(A)
S = C.dot(A)
P = M + S

In [40]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
np.array_equiv(A.dot(B), A.dot(A))

False

In [43]:
np.array_equiv(A.dot(S), A.dot(C))

False

In [44]:
np.array_equiv(A.dot(L), G)

True

In [45]:
np.array_equiv(L.dot(A), P)

True

In [46]:
A.dot(1)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  5]])

In [47]:
A.dot(0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## Determinant

The determinant is a special number that can be calculated from a matrix. It has to be a square matrix in order to proceed. Cross multiplication is the process to perform determinant in matrix.

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}0&5\\2&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [48]:
A = np.array([
    [0,5],
    [2,3]
])
np.linalg.det(A)

-9.999999999999998

In [49]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
M = np.array([
    [1,9,8,9],
    [2,0,0,3],
    [1,9,9,7],
    [2,0,0,2]
])
np.linalg.det(M)

18.000000000000004

## Inverse

Inverse of a Matrix is one of the matrix where multiplying the given matrix, which shows multiplicative identity. It is denoted as A^-1. 








The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}0&5\\-2&3\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (0)(3)-(5)(-2) = 10$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [50]:
M = np.array([
    [0,5,4],
    [2,3,5],
    [3,4,5]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 1]])

In [51]:
P = np.array([
               [2,1,3],
               [3,1,5],
               [6,8,6]
])
Q = np.linalg.inv(P)
Q

array([[17. , -9. , -1. ],
       [-6. ,  3. ,  0.5],
       [-9. ,  5. ,  0.5]])

To validate the whether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

```
# This is formatted as code
```



In [52]:
squad = np.array([
    [0.23, 1.3, 0.45],
    [4.67, 2.7, 2.9],
    [2.3, 1.5, 8.5]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade

array([[0.576],
       [3.214],
       [5.86 ]])

## Activity

### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [53]:
A = np.array([
    [4,3,2,1],
    [5,6,7,8],
    [9,10,11,12],
    [5,6,7,5]
])
B = np.array([
    [0,0,0,2],
    [0,0,2,3],
    [0,2,1,3],
    [3,1,5,3]
])
C= np.array([
  [2,1,3,5],
  [6,7,8,9],
  [9,8,6,4],
  [12,13,14,15]
])

In [54]:
D = A.dot(B)
E = A.dot(C)
F = B.dot(C)
G = B + C
H = D + E

In [55]:
I = B.dot(A)
J = C.dot(A)
K = I + J

**Property No.1**

In [56]:
print('PROPERTY NO. 1')
print(f'Is AB=BA?:  {np.array_equiv(D, I)}')
print('Matrix AB:')
print(np.matmul(A,B))
print(f'Shape:\t{np.matmul(A,B).shape}')
print('Matrix BA:')
print(np.matmul(B,A))
print(f'Shape:\t{np.matmul(B,A).shape}')
print('PROPERTY PROVEN!')

PROPERTY NO. 1
Is AB=BA?:  False
Matrix AB:
[[  3   5  13  26]
 [ 24  22  59  73]
 [ 36  34  91 117]
 [ 15  19  44  64]]
Shape:	(4, 4)
Matrix BA:
[[10 12 14 10]
 [33 38 43 39]
 [34 40 46 43]
 [77 83 89 86]]
Shape:	(4, 4)
PROPERTY PROVEN!


**Property No.2**

In [57]:
print('PROPERTY NO. 2')
print(f'Is A(BC)=(AB)C?:  {np.array_equiv(A.dot(F),D.dot(C))}')
print('Matrix A(BC):')
print(np.matmul(A,F))
print(f'Shape:\t{np.matmul(A,F).shape}')
print('Matrix (AB)C:')
print(np.matmul(D,C))
print(f'Shape:\t{np.matmul(D,C).shape}')
print('PROPERTY PROVEN!')

PROPERTY NO. 2
Is A(BC)=(AB)C?:  True
Matrix A(BC):
[[ 465  480  491  502]
 [1587 1599 1624 1649]
 [2499 2523 2564 2605]
 [1308 1332 1357 1382]]
Shape:	(4, 4)
Matrix (AB)C:
[[ 465  480  491  502]
 [1587 1599 1624 1649]
 [2499 2523 2564 2605]
 [1308 1332 1357 1382]]
Shape:	(4, 4)
PROPERTY PROVEN!


**Property No.3**

In [58]:
print('PROPERTY NO. 3')
print(f'Is A(B+C)=(AB)+(AC)?:  {np.array_equiv(A.dot(G),H)}')
print('Matrix A(B+C):')
print(np.matmul(A,G))
print(f'Shape:\t{np.matmul(A,G).shape}')
print('Matrix (AB)+(AC):')
print(np.add(D,E))
print(f'Shape:\t{np.add(D,E).shape}')
print('PROPERTY PROVEN!')

PROPERTY NO. 3
Is A(B+C)=(AB)+(AC)?:  True
Matrix A(B+C):
[[ 59  59  75  96]
 [229 229 276 300]
 [357 357 432 476]
 [184 187 219 246]]
Shape:	(4, 4)
Matrix (AB)+(AC):
[[ 59  59  75  96]
 [229 229 276 300]
 [357 357 432 476]
 [184 187 219 246]]
Shape:	(4, 4)
PROPERTY PROVEN!


Property No.4

In [59]:
print('PROPERTY NO. 4')
print(f'Is (B+C)A=(BA)+(CA)?:  {np.array_equiv(G.dot(A),K)}')
print('Matrix (B+C)A:')
print(np.matmul(G,A))
print(f'Shape:\t{np.matmul(G,A).shape}')
print('Matrix (BA)+(CA):')
print(np.add(I,J))
print(f'Shape:\t{np.add(I,J).shape}')
print('PROPERTY PROVEN!')

PROPERTY NO. 4
Is (B+C)A=(BA)+(CA)?:  True
Matrix (B+C)A:
[[ 75  84  93  81]
 [209 232 255 242]
 [184 199 214 208]
 [391 427 463 445]]
Shape:	(4, 4)
Matrix (BA)+(CA):
[[ 75  84  93  81]
 [209 232 255 242]
 [184 199 214 208]
 [391 427 463 445]]
Shape:	(4, 4)
PROPERTY PROVEN!


**Property No.5**

In [60]:
print('PROPERTY NO. 5')
print(f'Is A(1)=A?:  {np.array_equiv(A.dot(1),A)}')
print('Matrix A(1):')
print(np.multiply(A,1))
print(f'Shape:\t{np.multiply(A,1).shape}')
print('Matrix A:')
print(A)
print(f'Shape:\t{A.shape}')
print('PROPERTY PROVEN!')

PROPERTY NO. 5
Is A(1)=A?:  True
Matrix A(1):
[[ 4  3  2  1]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 5  6  7  5]]
Shape:	(4, 4)
Matrix A:
[[ 4  3  2  1]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 5  6  7  5]]
Shape:	(4, 4)
PROPERTY PROVEN!


**Property No.6**

In [61]:
print('PROPERTY NO. 6')
print(f'Is A(0)=0?:  {np.array_equiv(A.dot(0),0)}')
print('Matrix A(0):')
print(np.multiply(A,0))
print(f'Shape:\t{np.multiply(A,0).shape}')
print('PROPERTY PROVEN!')

PROPERTY NO. 6
Is A(0)=0?:  True
Matrix A(0):
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Shape:	(4, 4)
PROPERTY PROVEN!


For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "how can matrix operations solve problems in healthcare?". 