<a href="https://colab.research.google.com/github/luizmaeaspillaga/LinearAlgebra_2ndSem/blob/main/Assignment_no_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for CHE
## Laboratory 4: Matrices

## Objectives
At the end of this activity you will be able to:
  1. Be familiar with matrices and their relation to linear equations.
  2. Perfoem basic matrix operations.
  3. Program and translate matrix equations and operations using Python.
  

## Discussion


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

Matrices


The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representation of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.

Let's say for example you have ***A*** and ***B ***as system of equation. 

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. $$

We could see that ***A*** is a system of 2 equations with 2 parameters. While ***B*** is a system of 3 equations with 3 parameters. We can represent them as matrices as:

:$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}
$$

## **Declaring Matrices**


Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be reprsented just like the equation below. Whereas A is a matrix consisting of elements denoted by a. Denoted by  is the number of rows in the matrix while  stands for the number of columns.
Do note that the  of a matrix is .

So assuming that you already discussed the fundamental representation of matrices, their types, and operations. We'll proceed doing them in here in Python. 

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

In [ ]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
  print(f'Matrix"\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Declaring a 2 x 2 matrix
A = np.array([
     [1, 2],
     [3, 1]
])
describe_mat(A)

Matrix"
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [ ]:
G = np.array([
    [1,1,3],
    [2,2,4]
])
describe_mat(G)

Matrix"
[[1 1 3]
 [2 2 4]]

Shape:	(2, 3)
Rank:	2



In [ ]:
## Declaring a 3 x 2 matrix
B = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat(B)

Matrix"
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [ ]:
H = np.array([1,2,3,4,5])
describe_mat(H)

Matrix"
[1 2 3 4 5]

Shape:	(5,)
Rank:	1



## Categorizing Matrices
There are several ways of classifying matrices. Once could be according to their shape and another is according to their **element values**. We'll try to go through them.

## **According to Shape**
## **Row and Column Matrices** 
Row and column matrices are used to represent row and column spaces of a bigger vector space. Moreover, these are represented by a single column or single row. Using this can make vector and matrix computations easier. The shape of row matrices would be $1 \times j$ and column matrices would be $i \times 1$.

In [ ]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    1, 3, 2, -4
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3, -4]       
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix"
[ 1  3  2 -4]

Shape:	(4,)
Rank:	1

Matrix"
[[ 1  2  3 -4]]

Shape:	(1, 4)
Rank:	2



In [ ]:
## Declaring a Column Matrix

col_mat = np.array([
    [2],
    [1],
    [3]
])
describe_mat(col_mat)

Matrix"
[[2]
 [1]
 [3]]

Shape:	(3, 1)
Rank:	2



## **Square Matrices**



A Square matrix represents both row and column matrices but with the same sizes. The shape of a square matrix can be presented as $i = j$.

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
  [2,1,3],
  [1,4,3],
  [6,1,29]     
])
non_square_mat = np.array([
[2,1,3],
[1,4,3]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[ 2  1  3]
 [ 1  4  3]
 [ 6  1 29]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[2 1 3]
 [1 4 3]]

Shape:	(2, 3)
Rank:	2
Is Square: False



## **According to element values**

## Null Matrix
A Null Matrix is a type of matrix that has no elements as it is always a subspace of any vector or matrix.

In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
      is_square = True if matrix.shape[0] == matrix.shape[1] else False
      print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
      print('Matrix is Null')


In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


## Zero Matrix

A Zero matrix considers any rectangular matrix with a value of 0 for all of its elements.


In [ ]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((1,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]]


## Ones Matrix

A ones matrix, almost similar to zero matrix, considers any rectangular matrix with a value of 1 for all its elements instead of 0

In [ ]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,4))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Diagonal Matrix

A diagonal matrix has the shape of a square matrix but only has values at the diagonal of the matrix.

In [ ]:
np.array([
    [2,0,0],
    [0,1,0],
    [0,0,3]
])

array([[2, 0, 0],
       [0, 1, 0],
       [0, 0, 3]])

In [ ]:
d = np.diag([2,1,3,4])
d.shape == d.shape[0] == d.shape[1]
d

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## Identity Matrix

In linear algebra, identity matrix is a square matrix that contains elements that are diagonal with value of one. While the rest of the matrix have the value of zero.


In [ ]:
np.eye(1)


array([[1.]])

In [ ]:
np.identity(1000)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

## Upper Triangular Matrix

Upper triangular matrix is also a square matrix where all entries below that main diagonal has no value or zero.

In [ ]:
np.array([
    [1,2,3,4],
    [2,1,2,-2],
    [0,0,5,2],
    [0,0,0,2]
])

array([[ 1,  2,  3,  4],
       [ 2,  1,  2, -2],
       [ 0,  0,  5,  2],
       [ 0,  0,  0,  2]])

## Lower Triangular Matrix

While on the other hand, lower triangular matrix is a square matrix where all the entries above the main daigonal has no value or zero.

In [ ]:
np.array([
    [1,0,0],
    [5,3,0],
    [7,8,5]
])

array([[1, 0, 0],
       [5, 3, 0],
       [7, 8, 5]])

## **Matrix Algebra**

# **Addition**

Addition of matrices is the operation of adding two matrices by adding the corresponding entries together. Two matrices can be added only if they have the same numbers of row and columns.





In [ ]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])
B = np.array([
    [2,2],
    [2,3],
    [7,9]
])
A+B

array([[ 3,  4],
       [ 4,  6],
       [11, 10]])

In [ ]:
52+A ##Broadcasting

array([[53, 54],
       [54, 55],
       [56, 53]])

## **Subtraction**

Subtraction of matrices deals with subtracting elements in each row and column from elements in row and columns. Like in addition, two matrices can be subtracted only if they have the same numbers of row and columns.

In [ ]:
A-B

array([[-1,  0],
       [ 0,  0],
       [-3, -8]])

In [ ]:
7-B

array([[ 5,  5],
       [ 5,  4],
       [ 0, -2]])

In [ ]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

## **Element-wise Multiplication**

In element-wise multiplication in matrix, every element present in the first matrix will be multiplies to the second matrix's element. Like in addition and subtraction, before performing element-wise multiplication make sure that the both matrices has the same dimensions. 

In [ ]:
A*B
np.multiply(A,B)

array([[ 2,  4],
       [ 4,  9],
       [28,  9]])

In [ ]:
2*A

array([[2, 4],
       [6, 2]])

## **Pratice**
1. Given the linear combination below, try to create a corresponding matrix representing it. 

:$$\theta = 5x + 3y - z$$

In [ ]:
def describe_mat(matrix):
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
theta = np.array ([
    [5,3,-1]
])
describe_mat(theta)

Matrix:
[[ 5  3 -1]]

Shape:	(1, 3)
Rank:	2



 2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs square: {is_square}\n')

In [ ]:
A = np.array ([
   [1,2,1],
   [0,4,-1],
   [0,0,10]                     
])

describe_mat(A)

Matrix:
[[ 1  2  1]
 [ 0  4 -1]
 [ 0  0 10]]

Shape:	(3, 3)
Rank:	2
Is square: True



3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown


In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

$$
G = \left\{\begin{array}
1x_1 + 7x_2 + 8x_3\\
4x_2 - x-3\\
10x_3
\end{array}right.
$$

$$
G = \begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7\end{bmatrix}
$$

$$
G = \left\{
    \begin{array}\
        1 + 7 + 8 \\
        2 + 2 + 2 \\
        4 + 6 + 7 \\
    \end{array}
\right. \\
 $$

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.

In [ ]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

$$
H = \begin{bmatrix} 1 & 0 & 0 \\ 2 & 2 & 0 \\ 4 & 6 & 7\end{bmatrix}
$$

$$
H = \left\{
    \begin{array}\
        1 + 0 + 0 \\
        2 + 2 + 0 \\
        4 + 6 + 7 \\
    \end{array}
\right. \\
 $$

## **Task 1**

In [ ]:
def mat_desc(mat):
    sq = False
    mat = np.array(mat)
    print(mat)
    print('Shape:', mat.shape)
    print('Size:', mat.size)
    print('Rank:', np.linalg.matrix_rank(mat))
    if(mat.shape[0] == mat.shape[1]):
        sq = True
        print('The matrix is square')
    else:
        print('The matrix is non-square')
    if(mat.shape[0] == 0 and mat.shape[1] == 0):
        print('The matrix is empty')
    else:
        print('The matrix is not empty')
    iden = np.identity(mat.shape[0])
    if(sq and (iden == mat).all()):
        print('The matrix is an identity matrix')
    else:
        print('The matrix is not an identity matrix')
    one = np.ones((mat.shape[0], mat.shape[1]))
    if((one == mat).all()):
        print('The matrix is an ones matrix')
    else:
        print('The matrix is not an ones matrix')
    zero = np.zeros((mat.shape[0], mat.shape[1]))
    if((zero == mat).all()):
        print('The matrix is an zeros matrix')
    else:
        print('The matrix is not a zeros matrix')

In [ ]:
print('Matrix 1:')
mat_desc([[1,2,3],[4,5,6],[7,8,9]])

Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Rank: 2
The matrix is square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix


In [ ]:
print('Matrix 2:')
mat_desc([[1,0,0],[0,1,0],[0,0,1]])


Matrix 2:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Shape: (3, 3)
Size: 9
Rank: 3
The matrix is square
The matrix is not empty
The matrix is an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix


In [ ]:
print('Matrix 3:')
mat_desc([[0,0,0],[0,0,0]])

Matrix 3:
[[0 0 0]
 [0 0 0]]
Shape: (2, 3)
Size: 6
Rank: 0
The matrix is non-square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is an zeros matrix


## **Task 2**

In [ ]:
import numpy as np
def mat_operation(a,b):
  r1=len(a)
  r2=len(b)
  c1=len(a[0])
  c2=len(b[0])
  if r1!=r2 and c1!=c2 :
    return "Operation not possible"
  #Compute the sum of the array
  s=a+b
  #Compute the difference
  d=a-b
  #Compute the dot product 
  p=a*b
  #Return the result
  return [s,d,p]
  #generate the 2 random matrices
x =  np.random.randint(100, size=(3, 3))
y =  np.random.randint(100, size=(3, 3))
print("x= ",x)
print("y= ",y)
[s,d,p]=mat_operation(x,y)
print("x+y",s)
print("x-y",d)
print("x*y",p)


x=  [[ 8  3 38]
 [77  8 45]
 [ 4 28 48]]
y=  [[16 10 16]
 [39 53 40]
 [58 96 32]]
x+y [[ 24  13  54]
 [116  61  85]
 [ 62 124  80]]
x-y [[ -8  -7  22]
 [ 38 -45   5]
 [-54 -68  16]]
x*y [[ 128   30  608]
 [3003  424 1800]
 [ 232 2688 1536]]
