<a href="https://colab.research.google.com/github/luizmaeaspillaga/LinearAlgebra_2ndSem/blob/main/Assignment_no_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for CHE
## Laboratory 4: Matrices

## Objectives
At the end of this activity you will be able to:
  1. Be familiar with matrices and their relation to linear equations.
  2. Perfoem basic matrix operations.
  3. Program and translate matrix equations and operations using Python.
  

## Discussion


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

Matrices


The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representation of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.

Let's say for example you have ***A*** and ***B ***as system of equation. 

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. $$

We could see that ***A*** is a system of 2 equations with 2 parameters. While ***B*** is a system of 3 equations with 3 parameters. We can represent them as matrices as:

:$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}
$$

So assuming that you already discussed the fundamental representation of matrices, their types, and operations. We'll proceed doing them in here in Python. 

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

In [8]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
  print(f'Matrix"\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [12]:
## Declaring a 2 x 2 matrix
A = np.array([
     [1, 2],
     [3, 1]
])
describe_mat(A)

Matrix"
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [14]:
G = np.array([
    [1,1,3],
    [2,2,4]
])
describe_mat(G)

Matrix"
[[1 1 3]
 [2 2 4]]

Shape:	(2, 3)
Rank:	2



In [13]:
H = np.array([1,2,3,4,5])
describe_mat(H)

Matrix"
[1 2 3 4 5]

Shape:	(5,)
Rank:	1



In [16]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    1, 3, 2, -4
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3, -4]       
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix"
[ 1  3  2 -4]

Shape:	(4,)
Rank:	1

Matrix"
[[ 1  2  3 -4]]

Shape:	(1, 4)
Rank:	2



In [20]:
## Declaring a Column Matrix

col_mat = np.array([
    [2],
    [1],
    [3]
])
describe_mat(col_mat)

Matrix"
[[2]
 [1]
 [3]]

Shape:	(3, 1)
Rank:	2



In [32]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [35]:
square_mat = np.array([
  [2,1,3],
  [1,4,3],
  [6,1,29]     
])
non_square_mat = np.array([
[2,1,3],
[1,4,3]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[ 2  1  3]
 [ 1  4  3]
 [ 6  1 29]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[2 1 3]
 [1 4 3]]

Shape:	(2, 3)
Rank:	2
Is Square: False



In [40]:
def describe_mat(matrix):
    if matrix.size > 0:
      is_square = True if matrix.shape[0] == matrix.shape[1] else False
      print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
      print('Matrix is Null')


In [42]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


In [43]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((1,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]]


In [45]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,4))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [46]:
np.array([
    [2,0,0],
    [0,1,0],
    [0,0,3]
])

array([[2, 0, 0],
       [0, 1, 0],
       [0, 0, 3]])

In [48]:
d = np.diag([2,1,3,4])
d.shape == d.shape[0] == d.shape[1]
d

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [52]:
np.eye(13)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [54]:
np.identity(1000)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [63]:
np.array([
    [1,2,3,4],
    [2,1,2,-2],
    [0,0,5,2],
    [0,0,0,2]
])

array([[ 1,  2,  3,  4],
       [ 2,  1,  2, -2],
       [ 0,  0,  5,  2],
       [ 0,  0,  0,  2]])

In [67]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])
B = np.array([
    [2,2],
    [2,3],
    [7,9]
])
A+B

array([[ 3,  4],
       [ 4,  6],
       [11, 10]])

In [70]:
52+A ##Broadcasting

array([[53, 54],
       [54, 55],
       [56, 53]])

In [71]:
A-B

array([[-1,  0],
       [ 0,  0],
       [-3, -8]])

In [72]:
7-B

array([[ 5,  5],
       [ 5,  4],
       [ 0, -2]])

## Pratice
1. Given the linear combination below, try to create a corresponding matrix representing it. 

:$$\theta = 5x + 3y - z$$

 2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown


In [65]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

$$
G = \left\{\begin{array}
1x_1 + 7x_2 + 8x_3\\
4x_2 - x-3\\
10x_3
\end{array}right.
$$

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.

In [66]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])